name: Rust

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install nextest
      run: cargo install cargo-nextest
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo nextest run --verbose
