name: Rust

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/rust.yml'
      - '**/*.rs'
      - 'Cargo.toml'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/rust.yml'
      - '**/*.rs'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with:
        tool: nextest
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo nextest run --verbose
